server:
  port: 18089

spring:
  rabbitmq:
    host: 192.168.10.102
    port: 5672
    virtual-host: /hmall
    username: admin
    password: admin
#spring:
#  rabbitmq:
#    connection-timeout: 1s # 设置MQ的连接超时时间
#    template:
#      retry:
#        enabled: true # 开启超时重试机制
#        initial-interval: 1000ms # 失败后的初始等待时间
#        multiplier: 1 # 失败后下次的等待时长倍数，下次等待时长 = initial-interval * multiplier
#        max-attempts: 3 # 最大重试次数
#hm:
#  jwt:
#    location: classpath:hmtrade.jks
#    alias: hmtrade
#    password: hmtrade123
#    tokenTTL: 30m
#  auth:
#    excludePaths:
#      - /search/**
#      - /users/login
#      - /items/**
#      - /hi
# keytool -genkeypair -alias hmall -keyalg RSA -keypass hmall123 -keystore hmall.jks -storepass hmall123
hm:
  db:
    databases: hm-trade
  swagger:
    title: 购物车接口文档
    package: com.hmall.item.controller
  cart:
    maxSize: 2 #购物车上限