server:
  port: 8082
  spring:
    application:
      name: cart-service
    profiles:
      active: dev
    cloud:
      nacos:
        discovery:
          server-addr: 192.168.10.102:8848
          config:
            file-configs:
              - dataId: shared-jdbc.yml
              - dataId: shared-log.yml
              - dataId: shared-swagger.yaml
              - dataId: shared-feign.yaml
spring:
  cloud:
    sentinel:
      transport:
        dashboard: 192.168.10.102:8090
      http-method-specify: true
#      datasource:
#        ds2:
#          nacos:
#            server-addr: 192.168.10.102:8848
#            data-id: degrade.json
#            group-id: DEFAULT_GROUP
#            data-type: json
#            rule-type: degrade
hm:
  db:
    databases: hm-cart
  swagger:
    title: 购物车接口文档
    package: com.hmall.cart.controller
  cart:
    maxSize: 2 #购物车上限

#hm:
#  jwt:
#    location: classpath:hmall.jks
#    alias: hmall
#    password: hmall123
#    tokenTTL: 30m
#  auth:
#    excludePaths:
#      - /search/**
#      - /users/login
#      - /items/**
#      - /hi
# keytool -genkeypair -alias hmall -keyalg RSA -keypass hmall123 -keystore hmall.jks -storepass hmall123
feign:
  sentinel:
    enabled: true