server:
  port: 10010
spring:
  application:
    name: gateway
  profiles:
    active: dev
  cloud:
    nacos:
        server-addr: 192.168.10.102:8848
    gateway:
      routes:
        - id: item-service
          uri: lb://item-service
          predicates:
            - Path=/items/**,/search/**
#          filters:
#            - AddRequestHeader=truth,Hege is good booy
        - id: user-service
          uri: lb://hm-user
          predicates:
            - Path=/addresses/**,/users/**
        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/carts/**
        - id: order-service
          uri: lb://hm-order
          predicates:
            - Path=/orders/**
        - id: pay-service
          uri: lb://hm-pay
          predicates:
            - Path=/pay-orders/**
      default-filters:
        - AddRequestHeader=truth,Hege is good booy
        - PrintAny=1,2,3
#        - name: PrintAny
#          args:
#            a: 1
#            b: 2
#            c: 3
logging:
  level:
    com.hmall: debug
  pattern:
    dateformat: HH:mm:ss:SSS
  file:
    path: "logs/${spring.application.name}"
hm:
  jwt:
    location: classpath:hmall.jks
    alias: hmall
    password: hmall123
    tokenTTL: 30m
  auth:
    excludePaths:
      - /search/**
      - /users/login
      - /items/**
      - /hi
# keytool -genkeypair -alias hmall -keyalg RSA -keypass hmall123 -keystore hmall.jks -storepass hmall123