server:
  port: 8080
spring:
  application:
    name: gateway
  profiles:
    active: dev
  cloud:
    gateway:
      routes:
        - id: item-service
          uri: lb://item-service
          predicates:
            - Path=/items/**,/search/**
        - id: item-service
          uri: lb://item-service
          predicates:
            - Path=/items/**,/search/**
logging:
  level:
    com.hmall: debug
  pattern:
    dateformat: HH:mm:ss:SSS
  file:
    path: "logs/${spring.application.name}"
#hm:
#  jwt:
#    location: classpath:hmall.jks
#    alias: hmall
#    password: hmall123
#    tokenTTL: 30m
#  auth:
#    excludePaths:
#      - /search/**
#      - /users/login
#      - /items/**
#      - /hi
# keytool -genkeypair -alias hmall -keyalg RSA -keypass hmall123 -keystore hmall.jks -storepass hmall123